version: '3.7'

services:
  db-postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'db-postgresql'
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb

volumes:
  database:
