version: '3.7'

services:
  db-postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'db-postgresql'
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - ./redis-data:/data

volumes:
  database:
  redis-data:
